# 作業提問

## k934. 質數
https://zerojudge.tw/ShowProblem?problemid=k934

## k970. 質因數分解
https://zerojudge.tw/ShowProblem?problemid=k970

## k971. 最小公倍數
https://zerojudge.tw/ShowProblem?problemid=k971

## 課程復習

In [1]:
import numpy as np

In [2]:
a = [1, 2, 3]  * 2
a

[1, 2, 3, 1, 2, 3]

In [3]:
b = [1, 2, 3]
b + b

[1, 2, 3, 1, 2, 3]

In [8]:
a_np = np.array([1, 2, 3])
a_np

array([1, 2, 3])

In [9]:
a_np * 2

array([2, 4, 6])

In [27]:
data = list(range(9))
a = np.array(data)
a.shape = (3, 3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### universal function

In [28]:
import math
math.sin(math.pi / 2)

1.0

In [29]:
import numpy as np
np.sin(math.pi/2)

1.0

In [31]:
np.sin(a)

array([[ 0.        ,  0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825]])

In [32]:
math.sin(a)

TypeError: only length-1 arrays can be converted to Python scalars

math 的 sin 函式一次只能處理一個數字

numpy 的 sin 函式一次能處理所有的 numpy array 的數字

In [34]:
import pandas as pd

In [37]:
tables = pd.read_html("https://zh.wikipedia.org/zh-tw/%E8%B4%A2%E5%AF%8C%E4%B8%96%E7%95%8C500%E5%BC%BA")

In [39]:
df = tables[0]

pandas 的資料組構主要有兩個東西

DataFrame - 類似 Table 的東西

Series - 類似 List 的東西 



In [41]:
df

排名            公司   國家/地區         產業 收入 (十億美元)
0   1           沃爾瑪      美國        零售業    $611.3
1   2  沙烏地阿拉伯國家石油公司  沙烏地阿拉伯         能源    $603.7
2   3          國家電網      中國         能源    $530.0
3   4         亞馬遜公司      美國  網際網路服務和零售    $514.0
4   5     中國石油天然氣集團      中國         石油    $483.1
5   6      中國石油化工集團      中國         石油    $471.2
6   7         艾克森美孚      美國         石油    $413.7
7   8          蘋果公司      美國         科技    $394.3
8   9            殼牌      英國         石油    $386.2
9  10        聯合健康集團      美國       健康護理    $324.2

In [45]:
type(df)

pandas.core.frame.DataFrame

In [47]:
df['公司']

0             沃爾瑪
1    沙烏地阿拉伯國家石油公司
2            國家電網
3           亞馬遜公司
4       中國石油天然氣集團
5        中國石油化工集團
6           艾克森美孚
7            蘋果公司
8              殼牌
9          聯合健康集團
Name: 公司, dtype: object

In [46]:
type(df['公司'])

pandas.core.series.Series

In [48]:
df['收入 (十億美元)']

0    $611.3
1    $603.7
2    $530.0
3    $514.0
4    $483.1
5    $471.2
6    $413.7
7    $394.3
8    $386.2
9    $324.2
Name: 收入 (十億美元), dtype: object

In [53]:
df.indexes = ['ranking', 'company', 'country/area', 'industry', 'income', 'income2']

C:\Users\charlie\AppData\Local\Temp\ipykernel_10376\1609996323.py:1: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  df.indexes = ['ranking', 'company', 'country/area', 'industry', 'income', 'income2']


In [52]:
df

排名            公司   國家/地區         產業 收入 (十億美元)  收入 X 2
0   1           沃爾瑪      美國        零售業    $611.3  $611.3
1   2  沙烏地阿拉伯國家石油公司  沙烏地阿拉伯         能源    $603.7  $603.7
2   3          國家電網      中國         能源    $530.0  $530.0
3   4         亞馬遜公司      美國  網際網路服務和零售    $514.0  $514.0
4   5     中國石油天然氣集團      中國         石油    $483.1  $483.1
5   6      中國石油化工集團      中國         石油    $471.2  $471.2
6   7         艾克森美孚      美國         石油    $413.7  $413.7
7   8          蘋果公司      美國         科技    $394.3  $394.3
8   9            殼牌      英國         石油    $386.2  $386.2
9  10        聯合健康集團      美國       健康護理    $324.2  $324.2

# 視覺班提問

np.ndarray(shape=(2,2), dtype=float, order='F')