# 作業提問

## k934. 質數
https://zerojudge.tw/ShowProblem?problemid=k934

## k970. 質因數分解
https://zerojudge.tw/ShowProblem?problemid=k970

## k971. 最小公倍數
https://zerojudge.tw/ShowProblem?problemid=k971

## 課程復習

In [1]:
import numpy as np

In [2]:
a = [1, 2, 3]  * 2
a

[1, 2, 3, 1, 2, 3]

In [3]:
b = [1, 2, 3]
b + b

[1, 2, 3, 1, 2, 3]

In [8]:
a_np = np.array([1, 2, 3])
a_np

array([1, 2, 3])

In [9]:
a_np * 2

array([2, 4, 6])

In [27]:
data = list(range(9))
a = np.array(data)
a.shape = (3, 3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### universal function

In [28]:
import math
math.sin(math.pi / 2)

1.0

In [29]:
import numpy as np
np.sin(math.pi/2)

1.0

In [31]:
np.sin(a)

array([[ 0.        ,  0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825]])

In [32]:
math.sin(a)

TypeError: only length-1 arrays can be converted to Python scalars

math 的 sin 函式一次只能處理一個數字

numpy 的 sin 函式一次能處理所有的 numpy array 的數字

In [34]:
import pandas as pd

In [37]:
tables = pd.read_html("https://zh.wikipedia.org/zh-tw/%E8%B4%A2%E5%AF%8C%E4%B8%96%E7%95%8C500%E5%BC%BA")

In [39]:
df = tables[0]

pandas 的資料組構主要有兩個東西

DataFrame - 類似 Table 的東西

Series - 類似 List 的東西 



In [41]:
df

排名            公司   國家/地區         產業 收入 (十億美元)
0   1           沃爾瑪      美國        零售業    $611.3
1   2  沙烏地阿拉伯國家石油公司  沙烏地阿拉伯         能源    $603.7
2   3          國家電網      中國         能源    $530.0
3   4         亞馬遜公司      美國  網際網路服務和零售    $514.0
4   5     中國石油天然氣集團      中國         石油    $483.1
5   6      中國石油化工集團      中國         石油    $471.2
6   7         艾克森美孚      美國         石油    $413.7
7   8          蘋果公司      美國         科技    $394.3
8   9            殼牌      英國         石油    $386.2
9  10        聯合健康集團      美國       健康護理    $324.2

In [45]:
type(df)

pandas.core.frame.DataFrame

In [47]:
df['公司']

0             沃爾瑪
1    沙烏地阿拉伯國家石油公司
2            國家電網
3           亞馬遜公司
4       中國石油天然氣集團
5        中國石油化工集團
6           艾克森美孚
7            蘋果公司
8              殼牌
9          聯合健康集團
Name: 公司, dtype: object

In [46]:
type(df['公司'])

pandas.core.series.Series

In [48]:
df['收入 (十億美元)']

0    $611.3
1    $603.7
2    $530.0
3    $514.0
4    $483.1
5    $471.2
6    $413.7
7    $394.3
8    $386.2
9    $324.2
Name: 收入 (十億美元), dtype: object

In [56]:
df.columns = ('ranking', 'company', 'country/area', 'industry', 'income', 'income2')

In [59]:
df['income'] = df['income'].apply(lambda x: float(x.replace("$", "")))

In [61]:
df['income2'] = df['income'] * 2

In [63]:
df.income

0    611.3
1    603.7
2    530.0
3    514.0
4    483.1
5    471.2
6    413.7
7    394.3
8    386.2
9    324.2
Name: income, dtype: float64

In [68]:
df.income.median()

477.15

In [75]:
grades = pd.read_csv('grades.csv')

In [78]:
grades

Last name      "First name"                  "SSN"          "Test1"  \
0     Alfalfa        "Aloysius"          "123-45-6789"             40.0   
1      Alfred      "University"          "123-12-1234"             41.0   
2       Gerty          "Gramma"          "567-89-0123"             41.0   
3     Android        "Electric"          "087-65-4321"             42.0   
4     Bumpkin            "Fred"          "456-78-9012"             43.0   
5      Rubble           "Betty"          "234-56-7890"             44.0   
6      Noshow           "Cecil"          "345-67-8901"             45.0   
7        Buff             "Bif"          "632-79-9939"             46.0   
8     Airpump          "Andrew"          "223-45-6789"             49.0   
9      Backus             "Jim"          "143-12-1234"             48.0   
10  Carnivore             "Art"          "565-89-0123"             44.0   
11      Dandy             "Jim"          "087-75-4321"             47.0   
12   Elephant             "Ima"          "456-71-9012"             45.0   
13   Franklin           "Benny"          "234-56-2890"             50.0   
14     George             "Boy"          "345-67-3901"             40.0   
15  Heffalump          "Harvey"          "632-79-9439"             30.0   

     "Test2"   "Test3"   "Test4"   "Final"  "Grade"  
0       90.0     100.0      83.0      49.0     "D-"  
1       97.0      96.0      97.0      48.0     "D+"  
2       80.0      60.0      40.0      44.0      "C"  
3       23.0      36.0      45.0      47.0     "B-"  
4       78.0      88.0      77.0      45.0     "A-"  
5       90.0      80.0      90.0      46.0     "C-"  
6       11.0      -1.0       4.0      43.0      "F"  
7       20.0      30.0      40.0      50.0     "B+"  
8        1.0      90.0     100.0      83.0      "A"  
9        1.0      97.0      96.0      97.0     "A+"  
10       1.0      80.0      60.0      40.0     "D+"  
11       1.0      23.0      36.0      45.0     "C+"  
12       1.0      78.0      88.0      77.0     "B-"  
13       1.0      90.0      80.0      90.0     "B-"  
14       1.0      11.0      -1.0       4.0      "B"  
15       1.0      20.0      30.0      40.0      "C"

In [80]:
grades.columns = ("last name", 'first name', 'ssn', 'test1', 'test2', 'test3', 'test4', 'final', 'grade')

In [82]:
grades

last name        first name                    ssn  test1  test2  test3  \
0     Alfalfa        "Aloysius"          "123-45-6789"   40.0   90.0  100.0   
1      Alfred      "University"          "123-12-1234"   41.0   97.0   96.0   
2       Gerty          "Gramma"          "567-89-0123"   41.0   80.0   60.0   
3     Android        "Electric"          "087-65-4321"   42.0   23.0   36.0   
4     Bumpkin            "Fred"          "456-78-9012"   43.0   78.0   88.0   
5      Rubble           "Betty"          "234-56-7890"   44.0   90.0   80.0   
6      Noshow           "Cecil"          "345-67-8901"   45.0   11.0   -1.0   
7        Buff             "Bif"          "632-79-9939"   46.0   20.0   30.0   
8     Airpump          "Andrew"          "223-45-6789"   49.0    1.0   90.0   
9      Backus             "Jim"          "143-12-1234"   48.0    1.0   97.0   
10  Carnivore             "Art"          "565-89-0123"   44.0    1.0   80.0   
11      Dandy             "Jim"          "087-75-4321"   47.0    1.0   23.0   
12   Elephant             "Ima"          "456-71-9012"   45.0    1.0   78.0   
13   Franklin           "Benny"          "234-56-2890"   50.0    1.0   90.0   
14     George             "Boy"          "345-67-3901"   40.0    1.0   11.0   
15  Heffalump          "Harvey"          "632-79-9439"   30.0    1.0   20.0   

    test4  final    grade  
0    83.0   49.0     "D-"  
1    97.0   48.0     "D+"  
2    40.0   44.0      "C"  
3    45.0   47.0     "B-"  
4    77.0   45.0     "A-"  
5    90.0   46.0     "C-"  
6     4.0   43.0      "F"  
7    40.0   50.0     "B+"  
8   100.0   83.0      "A"  
9    96.0   97.0     "A+"  
10   60.0   40.0     "D+"  
11   36.0   45.0     "C+"  
12   88.0   77.0     "B-"  
13   80.0   90.0     "B-"  
14   -1.0    4.0      "B"  
15   30.0   40.0      "C"

In [84]:
names = ['last name', 'first name', 'grade']
grades[names]

last name        first name    grade
0     Alfalfa        "Aloysius"     "D-"
1      Alfred      "University"     "D+"
2       Gerty          "Gramma"      "C"
3     Android        "Electric"     "B-"
4     Bumpkin            "Fred"     "A-"
5      Rubble           "Betty"     "C-"
6      Noshow           "Cecil"      "F"
7        Buff             "Bif"     "B+"
8     Airpump          "Andrew"      "A"
9      Backus             "Jim"     "A+"
10  Carnivore             "Art"     "D+"
11      Dandy             "Jim"     "C+"
12   Elephant             "Ima"     "B-"
13   Franklin           "Benny"     "B-"
14     George             "Boy"      "B"
15  Heffalump          "Harvey"      "C"

In [87]:
grades[['last name', 'first name', 'grade']]

last name        first name    grade
0     Alfalfa        "Aloysius"     "D-"
1      Alfred      "University"     "D+"
2       Gerty          "Gramma"      "C"
3     Android        "Electric"     "B-"
4     Bumpkin            "Fred"     "A-"
5      Rubble           "Betty"     "C-"
6      Noshow           "Cecil"      "F"
7        Buff             "Bif"     "B+"
8     Airpump          "Andrew"      "A"
9      Backus             "Jim"     "A+"
10  Carnivore             "Art"     "D+"
11      Dandy             "Jim"     "C+"
12   Elephant             "Ima"     "B-"
13   Franklin           "Benny"     "B-"
14     George             "Boy"      "B"
15  Heffalump          "Harvey"      "C"

In [88]:
grades

last name        first name                    ssn  test1  test2  test3  \
0     Alfalfa        "Aloysius"          "123-45-6789"   40.0   90.0  100.0   
1      Alfred      "University"          "123-12-1234"   41.0   97.0   96.0   
2       Gerty          "Gramma"          "567-89-0123"   41.0   80.0   60.0   
3     Android        "Electric"          "087-65-4321"   42.0   23.0   36.0   
4     Bumpkin            "Fred"          "456-78-9012"   43.0   78.0   88.0   
5      Rubble           "Betty"          "234-56-7890"   44.0   90.0   80.0   
6      Noshow           "Cecil"          "345-67-8901"   45.0   11.0   -1.0   
7        Buff             "Bif"          "632-79-9939"   46.0   20.0   30.0   
8     Airpump          "Andrew"          "223-45-6789"   49.0    1.0   90.0   
9      Backus             "Jim"          "143-12-1234"   48.0    1.0   97.0   
10  Carnivore             "Art"          "565-89-0123"   44.0    1.0   80.0   
11      Dandy             "Jim"          "087-75-4321"   47.0    1.0   23.0   
12   Elephant             "Ima"          "456-71-9012"   45.0    1.0   78.0   
13   Franklin           "Benny"          "234-56-2890"   50.0    1.0   90.0   
14     George             "Boy"          "345-67-3901"   40.0    1.0   11.0   
15  Heffalump          "Harvey"          "632-79-9439"   30.0    1.0   20.0   

    test4  final    grade  
0    83.0   49.0     "D-"  
1    97.0   48.0     "D+"  
2    40.0   44.0      "C"  
3    45.0   47.0     "B-"  
4    77.0   45.0     "A-"  
5    90.0   46.0     "C-"  
6     4.0   43.0      "F"  
7    40.0   50.0     "B+"  
8   100.0   83.0      "A"  
9    96.0   97.0     "A+"  
10   60.0   40.0     "D+"  
11   36.0   45.0     "C+"  
12   88.0   77.0     "B-"  
13   80.0   90.0     "B-"  
14   -1.0    4.0      "B"  
15   30.0   40.0      "C"

### 讀檔與存檔

In [91]:
grades = pd.read_csv('grades.csv')

In [89]:
grades.to_csv("grades2.csv")

# 視覺班提問

np.ndarray(shape=(2,2), dtype=float, order='F')