# 作業提問

## k934. 質數
https://zerojudge.tw/ShowProblem?problemid=k934

## k970. 質因數分解
https://zerojudge.tw/ShowProblem?problemid=k970

## k971. 最小公倍數
https://zerojudge.tw/ShowProblem?problemid=k971

## 課程復習

In [1]:
import numpy as np

In [2]:
a = [1, 2, 3]  * 2
a

[1, 2, 3, 1, 2, 3]

In [3]:
b = [1, 2, 3]
b + b

[1, 2, 3, 1, 2, 3]

In [8]:
a_np = np.array([1, 2, 3])
a_np

array([1, 2, 3])

In [9]:
a_np * 2

array([2, 4, 6])

In [27]:
data = list(range(9))
a = np.array(data)
a.shape = (3, 3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### universal function

In [28]:
import math
math.sin(math.pi / 2)

1.0

In [29]:
import numpy as np
np.sin(math.pi/2)

1.0

In [31]:
np.sin(a)

array([[ 0.        ,  0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825]])

In [32]:
math.sin(a)

TypeError: only length-1 arrays can be converted to Python scalars

In [ ]:
math 的 sin 函式一次只能處理一個數字

numpy 的 sin 函式一次能處理所有的 

# 視覺班提問

np.ndarray(shape=(2,2), dtype=float, order='F')