# 作業提問

## k934. 質數
https://zerojudge.tw/ShowProblem?problemid=k934

## k970. 質因數分解
https://zerojudge.tw/ShowProblem?problemid=k970

## k971. 最小公倍數
https://zerojudge.tw/ShowProblem?problemid=k971

## 課程復習

In [1]:
import numpy as np

In [2]:
a = [1, 2, 3]  * 2
a

[1, 2, 3, 1, 2, 3]

In [3]:
b = [1, 2, 3]
b + b

[1, 2, 3, 1, 2, 3]

In [8]:
a_np = np.array([1, 2, 3])
a_np

array([1, 2, 3])

In [9]:
a_np * 2

array([2, 4, 6])

In [23]:
data = list(range(9))
a = np.ndarray(data=data, shape=(3, 3))
a.shapes = (3, 3)

TypeError: 'data' is an invalid keyword argument for ndarray()

In [22]:
np.ndarray(shape=(2,2), dtype=float, order='F')

array([[6.23042070e-307, 1.69121096e-306],
       [4.67296746e-307, 8.99004842e-312]])

# 視覺班提問

np.ndarray(shape=(2,2), dtype=float, order='F')