In [3]:
import cv2
import pandas as pd
import numpy as np
from plotly import express as px

自動排程

https://pypi.org/project/APScheduler/

In [6]:
n

array([[[0., 0., 0.],
        [0., 0., 0.]]])

In [17]:
df = pandas.read_csv('titanic_train.csv')
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [19]:
series = df['Fare']
series

0       7.2500
1      71.2833
2       7.9250
3      53.1000
4       8.0500
        ...   
886    13.0000
887    30.0000
888    23.4500
889    30.0000
890     7.7500
Name: Fare, Length: 891, dtype: float64

In [20]:
series.mean()

32.204207968574636

In [21]:
titanic_train.mean()

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [22]:
titanic_train[['Age', 'Fare']]

Age     Fare
0    22.0   7.2500
1    38.0  71.2833
2    26.0   7.9250
3    35.0  53.1000
4    35.0   8.0500
..    ...      ...
886  27.0  13.0000
887  19.0  30.0000
888   NaN  23.4500
889  26.0  30.0000
890  32.0   7.7500

[891 rows x 2 columns]

In [23]:
titanic_train[['Age', 'Fare']].mean()

Age     29.699118
Fare    32.204208
dtype: float64

In [25]:
series['Fare']

KeyError: 'Fare'

In [29]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

## pandas merge

In [30]:
df1 = df[['PassengerId', 'Name', 'Sex', 'Age']]
df1

PassengerId                                               Name     Sex  \
0              1                            Braund, Mr. Owen Harris    male   
1              2  Cumings, Mrs. John Bradley (Florence Briggs Th...  female   
2              3                             Heikkinen, Miss. Laina  female   
3              4       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female   
4              5                           Allen, Mr. William Henry    male   
..           ...                                                ...     ...   
886          887                              Montvila, Rev. Juozas    male   
887          888                       Graham, Miss. Margaret Edith  female   
888          889           Johnston, Miss. Catherine Helen "Carrie"  female   
889          890                              Behr, Mr. Karl Howell    male   
890          891                                Dooley, Mr. Patrick    male   

      Age  
0    22.0  
1    38.0  
2    26.0  
3    35.0  
4    35.0  
..    ...  
886  27.0  
887  19.0  
888   NaN  
889  26.0  
890  32.0  

[891 rows x 4 columns]

In [33]:
df2 = df[['PassengerId', 'Ticket', 'Fare', 'Cabin', 'Embarked']]
df2

PassengerId            Ticket     Fare Cabin Embarked
0              1         A/5 21171   7.2500   NaN        S
1              2          PC 17599  71.2833   C85        C
2              3  STON/O2. 3101282   7.9250   NaN        S
3              4            113803  53.1000  C123        S
4              5            373450   8.0500   NaN        S
..           ...               ...      ...   ...      ...
886          887            211536  13.0000   NaN        S
887          888            112053  30.0000   B42        S
888          889        W./C. 6607  23.4500   NaN        S
889          890            111369  30.0000  C148        C
890          891            370376   7.7500   NaN        Q

[891 rows x 5 columns]

In [36]:
pd3 = pd.merge(left=df1, right=df2, on=["PassengerId"])
pd3

PassengerId                                               Name     Sex  \
0              1                            Braund, Mr. Owen Harris    male   
1              2  Cumings, Mrs. John Bradley (Florence Briggs Th...  female   
2              3                             Heikkinen, Miss. Laina  female   
3              4       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female   
4              5                           Allen, Mr. William Henry    male   
..           ...                                                ...     ...   
886          887                              Montvila, Rev. Juozas    male   
887          888                       Graham, Miss. Margaret Edith  female   
888          889           Johnston, Miss. Catherine Helen "Carrie"  female   
889          890                              Behr, Mr. Karl Howell    male   
890          891                                Dooley, Mr. Patrick    male   

      Age            Ticket     Fare Cabin Embarked  
0    22.0         A/5 21171   7.2500   NaN        S  
1    38.0          PC 17599  71.2833   C85        C  
2    26.0  STON/O2. 3101282   7.9250   NaN        S  
3    35.0            113803  53.1000  C123        S  
4    35.0            373450   8.0500   NaN        S  
..    ...               ...      ...   ...      ...  
886  27.0            211536  13.0000   NaN        S  
887  19.0            112053  30.0000   B42        S  
888   NaN        W./C. 6607  23.4500   NaN        S  
889  26.0            111369  30.0000  C148        C  
890  32.0            370376   7.7500   NaN        Q  

[891 rows x 8 columns]

In [42]:
df1 = pd.DataFrame([{'col': 1, 'row': 2, 'data': 3}, {'col': 2, 'row': 3, 'data': 4}])
df1

col  row  data
0    1    2     3
1    2    3     4

In [45]:
df2 = pd.DataFrame([{'col': 2, 'row': 3, 'Label': 'Label2'}, {'col': 1, 'row': 2, 'Label': 'Label1'}])
df2

col  row   Label
0    2    3  Label2
1    1    2  Label1

In [46]:
pd.merge(left=df1, right=df2, on=['col', 'row'])

col  row  data   Label
0    1    2     3  Label1
1    2    3     4  Label2

In [68]:
fares = numpy.array(df['Fare'])
fares

array([  7.25  ,  71.2833,   7.925 ,  53.1   ,   8.05  ,   8.4583,
        51.8625,  21.075 ,  11.1333,  30.0708,  16.7   ,  26.55  ,
         8.05  ,  31.275 ,   7.8542,  16.    ,  29.125 ,  13.    ,
        18.    ,   7.225 ,  26.    ,  13.    ,   8.0292,  35.5   ,
        21.075 ,  31.3875,   7.225 , 263.    ,   7.8792,   7.8958,
        27.7208, 146.5208,   7.75  ,  10.5   ,  82.1708,  52.    ,
         7.2292,   8.05  ,  18.    ,  11.2417,   9.475 ,  21.    ,
         7.8958,  41.5792,   7.8792,   8.05  ,  15.5   ,   7.75  ,
        21.6792,  17.8   ,  39.6875,   7.8   ,  76.7292,  26.    ,
        61.9792,  35.5   ,  10.5   ,   7.2292,  27.75  ,  46.9   ,
         7.2292,  80.    ,  83.475 ,  27.9   ,  27.7208,  15.2458,
        10.5   ,   8.1583,   7.925 ,   8.6625,  10.5   ,  46.9   ,
        73.5   ,  14.4542,  56.4958,   7.65  ,   7.8958,   8.05  ,
        29.    ,  12.475 ,   9.    ,   9.5   ,   7.7875,  47.1   ,
        10.5   ,  15.85  ,  34.375 ,   8.05  , 263.    ,   8.0

## pandas 10 minutes tutorial
https://pandas.pydata.org/docs/user_guide/10min.html

In [72]:
array1 = np.array([1, 2, 3, 4])
array2 = np.array([5, 6, 7, 8])

In [73]:
array1

array([1, 2, 3, 4])

In [74]:
array2

array([5, 6, 7, 8])

In [75]:
list1 = [1, 2, 3, 4]
list2 = [5, 6, 7, 8]

In [76]:
list1

[1, 2, 3, 4]

In [77]:
list2

[5, 6, 7, 8]

In [78]:
list1

[1, 2, 3, 4]

In [81]:
array1

array([1, 2, 3, 4])

In [82]:
list1 * 2

[1, 2, 3, 4, 1, 2, 3, 4]