In [3]:
import cv2
import pandas as pd
import numpy as np
from plotly import express as px

自動排程

https://pypi.org/project/APScheduler/

In [6]:
n

array([[[0., 0., 0.],
        [0., 0., 0.]]])

In [184]:
df = pd.read_csv('titanic_train.csv')
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [19]:
series = df['Fare']
series

0       7.2500
1      71.2833
2       7.9250
3      53.1000
4       8.0500
        ...   
886    13.0000
887    30.0000
888    23.4500
889    30.0000
890     7.7500
Name: Fare, Length: 891, dtype: float64

In [20]:
series.mean()

32.204207968574636

In [21]:
titanic_train.mean()

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [22]:
titanic_train[['Age', 'Fare']]

Age     Fare
0    22.0   7.2500
1    38.0  71.2833
2    26.0   7.9250
3    35.0  53.1000
4    35.0   8.0500
..    ...      ...
886  27.0  13.0000
887  19.0  30.0000
888   NaN  23.4500
889  26.0  30.0000
890  32.0   7.7500

[891 rows x 2 columns]

In [23]:
titanic_train[['Age', 'Fare']].mean()

Age     29.699118
Fare    32.204208
dtype: float64

In [25]:
series['Fare']

KeyError: 'Fare'

In [29]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

## pandas merge

In [30]:
df1 = df[['PassengerId', 'Name', 'Sex', 'Age']]
df1

PassengerId                                               Name     Sex  \
0              1                            Braund, Mr. Owen Harris    male   
1              2  Cumings, Mrs. John Bradley (Florence Briggs Th...  female   
2              3                             Heikkinen, Miss. Laina  female   
3              4       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female   
4              5                           Allen, Mr. William Henry    male   
..           ...                                                ...     ...   
886          887                              Montvila, Rev. Juozas    male   
887          888                       Graham, Miss. Margaret Edith  female   
888          889           Johnston, Miss. Catherine Helen "Carrie"  female   
889          890                              Behr, Mr. Karl Howell    male   
890          891                                Dooley, Mr. Patrick    male   

      Age  
0    22.0  
1    38.0  
2    26.0  
3    35.0  
4    35.0  
..    ...  
886  27.0  
887  19.0  
888   NaN  
889  26.0  
890  32.0  

[891 rows x 4 columns]

In [33]:
df2 = df[['PassengerId', 'Ticket', 'Fare', 'Cabin', 'Embarked']]
df2

PassengerId            Ticket     Fare Cabin Embarked
0              1         A/5 21171   7.2500   NaN        S
1              2          PC 17599  71.2833   C85        C
2              3  STON/O2. 3101282   7.9250   NaN        S
3              4            113803  53.1000  C123        S
4              5            373450   8.0500   NaN        S
..           ...               ...      ...   ...      ...
886          887            211536  13.0000   NaN        S
887          888            112053  30.0000   B42        S
888          889        W./C. 6607  23.4500   NaN        S
889          890            111369  30.0000  C148        C
890          891            370376   7.7500   NaN        Q

[891 rows x 5 columns]

In [36]:
pd3 = pd.merge(left=df1, right=df2, on=["PassengerId"])
pd3

PassengerId                                               Name     Sex  \
0              1                            Braund, Mr. Owen Harris    male   
1              2  Cumings, Mrs. John Bradley (Florence Briggs Th...  female   
2              3                             Heikkinen, Miss. Laina  female   
3              4       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female   
4              5                           Allen, Mr. William Henry    male   
..           ...                                                ...     ...   
886          887                              Montvila, Rev. Juozas    male   
887          888                       Graham, Miss. Margaret Edith  female   
888          889           Johnston, Miss. Catherine Helen "Carrie"  female   
889          890                              Behr, Mr. Karl Howell    male   
890          891                                Dooley, Mr. Patrick    male   

      Age            Ticket     Fare Cabin Embarked  
0    22.0         A/5 21171   7.2500   NaN        S  
1    38.0          PC 17599  71.2833   C85        C  
2    26.0  STON/O2. 3101282   7.9250   NaN        S  
3    35.0            113803  53.1000  C123        S  
4    35.0            373450   8.0500   NaN        S  
..    ...               ...      ...   ...      ...  
886  27.0            211536  13.0000   NaN        S  
887  19.0            112053  30.0000   B42        S  
888   NaN        W./C. 6607  23.4500   NaN        S  
889  26.0            111369  30.0000  C148        C  
890  32.0            370376   7.7500   NaN        Q  

[891 rows x 8 columns]

In [42]:
df1 = pd.DataFrame([{'col': 1, 'row': 2, 'data': 3}, {'col': 2, 'row': 3, 'data': 4}])
df1

col  row  data
0    1    2     3
1    2    3     4

In [45]:
df2 = pd.DataFrame([{'col': 2, 'row': 3, 'Label': 'Label2'}, {'col': 1, 'row': 2, 'Label': 'Label1'}])
df2

col  row   Label
0    2    3  Label2
1    1    2  Label1

In [46]:
pd.merge(left=df1, right=df2, on=['col', 'row'])

col  row  data   Label
0    1    2     3  Label1
1    2    3     4  Label2

In [ ]:
fares = numpy.array(df['Fare'])
fares

## pandas 10 minutes tutorial
https://pandas.pydata.org/docs/user_guide/10min.html

In [72]:
array1 = np.array([1, 2, 3, 4])
array2 = np.array([5, 6, 7, 8])

In [73]:
array1

array([1, 2, 3, 4])

In [74]:
array2

array([5, 6, 7, 8])

In [75]:
list1 = [1, 2, 3, 4]
list2 = [5, 6, 7, 8]

In [76]:
list1

[1, 2, 3, 4]

In [77]:
list2

[5, 6, 7, 8]

In [78]:
list1

[1, 2, 3, 4]

In [81]:
array1

array([1, 2, 3, 4])

In [82]:
list1 * 2

[1, 2, 3, 4, 1, 2, 3, 4]

In [83]:
array1 * 2

array([2, 4, 6, 8])

In [84]:
array1

array([1, 2, 3, 4])

In [85]:
array1 * array2

array([ 5, 12, 21, 32])

In [86]:
list1 * list2

TypeError: can't multiply sequence by non-int of type 'list'

In [87]:
array1 + array2

array([ 6,  8, 10, 12])

In [88]:
array1 - array2

array([-4, -4, -4, -4])

In [89]:
array1 * array2

array([ 5, 12, 21, 32])

In [90]:
array1 / array2

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [101]:
nd1 = np.array([[1, 2], [3, 4]])
nd1

array([[1, 2],
       [3, 4]])

In [104]:
nd2 = np.array([[5, 6], [7, 8]])
nd2

array([[5, 6],
       [7, 8]])

In [107]:
nd1 * nd2

array([[ 5, 12],
       [21, 32]])

In [111]:
nd1[:, 0:]

array([[1, 2],
       [3, 4]])

In [112]:
np.array([[1, 2, 3]]).transpose()

array([[1],
       [2],
       [3]])

# 影像專班提問

In [1]:
import cv2
from plotly import express as px

* 讀出彩色圖，g使用cv2.imshow()，title用"Step 01"
* 轉成灰階，使用cv2秀圖，title用"Step 02"
* 秀出 Thresholing 的圖, title用"Step 03"
* 秀出 erode 或 dilate 處理完的結果，title用"Step 04"

In [ ]:
img = cv2.imread('A229.png')
px.imshow(img)

In [4]:
cv2.imshow('Step 01', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [6]:
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

In [ ]:
px.imshow(gray, color_continuous_scale='gray')

In [22]:
result = cv2.threshold(gray, 250, 255, cv2.THRESH_BINARY)

In [23]:
t, t_img = result

In [ ]:
px.imshow(t_img, color_continuous_scale='gray')

In [27]:
t_img_2 = 256 - t_img

In [ ]:
px.imshow(t_img_2, color_continuous_scale='gray')

In [110]:
kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (7, 7))

In [111]:
kernel

array([[0, 0, 0, 1, 0, 0, 0],
       [0, 1, 1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [0, 1, 1, 1, 1, 1, 0],
       [0, 0, 0, 1, 0, 0, 0]], dtype=uint8)

In [112]:
dilated = cv2.erode(src=t_img_2, kernel=kernel)

In [ ]:
px.imshow(dilated, color_continuous_scale='gray')

In [114]:
opened = cv2.dilate(src=dilated, kernel=kernel)

In [ ]:
px.imshow(opened, color_continuous_scale='gray')

先侵蝕(erode)再膨帳(Dilate) 清除白色雜訊

先膨帳(dilate) 再侵蝕 (erode) 清除黑色雜訊

In [116]:
dilated = cv2.dilate(src=opened, kernel=kernel)
closed = cv2.erode(src=dilated, kernel=kernel)

In [ ]:
px.imshow(closed, color_continuous_scale='gray')

# 綜合題問

In [159]:
import pandas as pd
import numpy as np

In [121]:
df = pd.read_csv('titanic_train.csv')

In [132]:
df.sort_values(['Survived', 'Age'], ascending=[False, True])

PassengerId  Survived  Pclass                                      Name  \
803          804         1       3           Thomas, Master. Assad Alexander   
755          756         1       2                 Hamalainen, Master. Viljo   
469          470         1       3             Baclini, Miss. Helene Barbara   
644          645         1       3                    Baclini, Miss. Eugenie   
78            79         1       2             Caldwell, Master. Alden Gates   
..           ...       ...     ...                                       ...   
859          860         0       3                          Razi, Mr. Raihed   
863          864         0       3         Sage, Miss. Dorothy Edith "Dolly"   
868          869         0       3               van Melkebeke, Mr. Philemon   
878          879         0       3                        Laleff, Mr. Kristo   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   

        Sex   Age  SibSp  Parch      Ticket     Fare Cabin Embarked  
803    male  0.42      0      1        2625   8.5167   NaN        C  
755    male  0.67      1      1      250649  14.5000   NaN        S  
469  female  0.75      2      1        2666  19.2583   NaN        C  
644  female  0.75      2      1        2666  19.2583   NaN        C  
78     male  0.83      0      2      248738  29.0000   NaN        S  
..      ...   ...    ...    ...         ...      ...   ...      ...  
859    male   NaN      0      0        2629   7.2292   NaN        C  
863  female   NaN      8      2    CA. 2343  69.5500   NaN        S  
868    male   NaN      0      0      345777   9.5000   NaN        S  
878    male   NaN      0      0      349217   7.8958   NaN        S  
888  female   NaN      1      2  W./C. 6607  23.4500   NaN        S  

[891 rows x 12 columns]

In [145]:
account_df = pd.DataFrame([{'id': 1, 'name': 'Richard'}, {'id': 2, 'name': 'Bruno'}, {'id': 3, 'name': 'Charlie'}, {'id': 3, 'name': 'Jenny'}])
account_df

id     name
0   1  Richard
1   2    Bruno
2   3  Charlie
3   3    Jenny

In [153]:
books_df = pd.DataFrame([{'id': 1000, 'user_id': 1, 'book': '哈利波特1'}, {'id': 1001, 'user_id': 2, 'book': '魔戒1'}, {'id': 1002, 'user_id': 1, 'book': '魔戒2'}, {'id': 1003, 'user_id': 4, 'book': '哈利波特 2' }])
books_df

id  user_id    book
0  1000        1   哈利波特1
1  1001        2     魔戒1
2  1002        1     魔戒2
3  1003        4  哈利波特 2

In [154]:
pd.merge(left=account_df, right=books_df, left_on='id', right_on='user_id')

id_x     name  id_y  user_id   book
0     1  Richard  1000        1  哈利波特1
1     1  Richard  1002        1    魔戒2
2     2    Bruno  1001        2    魔戒1

In [155]:
pd.merge(left=account_df, right=books_df, left_on='id', right_on='user_id', how='left')

id_x     name    id_y  user_id   book
0     1  Richard  1000.0      1.0  哈利波特1
1     1  Richard  1002.0      1.0    魔戒2
2     2    Bruno  1001.0      2.0    魔戒1
3     3  Charlie     NaN      NaN    NaN
4     3    Jenny     NaN      NaN    NaN

In [156]:
pd.merge(left=account_df, right=books_df, left_on='id', right_on='user_id', how='right')

id_x     name  id_y  user_id    book
0   1.0  Richard  1000        1   哈利波特1
1   2.0    Bruno  1001        2     魔戒1
2   1.0  Richard  1002        1     魔戒2
3   NaN      NaN  1003        4  哈利波特 2

In [157]:
books_owners = pd.merge(left=account_df, right=books_df, left_on='id', right_on='user_id', how='right')

In [167]:
books_owners['id_x'][3]

numpy.float64

In [171]:
books_owners[np.isnan(books_owners['id_x'])]

id_x name  id_y  user_id    book
3   NaN  NaN  1003        4  哈利波特 2

In [175]:
owners = pd.merge(left=account_df, right=books_df, left_on='id', right_on='user_id')
owners

id_x     name  id_y  user_id   book
0     1  Richard  1000        1  哈利波特1
1     1  Richard  1002        1    魔戒2
2     2    Bruno  1001        2    魔戒1

In [182]:
owners.groupby('user_id').size()

user_id
1    2
2    1
dtype: int64

In [185]:
df = pd.read_csv('titanic_train.csv')
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [192]:
df['Age'].min()

0.42

In [193]:
df['Age'].max()

80.0

In [194]:
df['Age'].mean()

29.69911764705882

In [204]:
df['Age'].median()

28.0

In [207]:
ages = df['Age']

# 告訴 jupyter, ages 的類別是 Series, 按 Tab 才有提示
ages: pd.Series = df['Age']

## 多線程(不是教學, 閒聊)

一個程執行一次就會產生一個 process

一個 process 可以有多個執行緒

python 不擅長 multi threading

如果要大量的平行處理, 且用到大量的CPU的話, 那就是建議 multiprocessing

如果只有大量的 I/O 但CPU 需求量低的話, multithreading 可以考慮

multiprocessing 吃的記憶體通常 > multithreading

multithreading 的每個 threading 之間有共享記憶體
