# 基礎班提問 13:30

# 影像班提問 14:30

# 綜合提問 15:30

# dash 練習

In [9]:
csv_file = 'https://raw.githubusercontent.com/plotly/datasets/master/solar.csv'

# 影像處理練習

## image convolution

In [10]:
!curl -O "https://upload.wikimedia.org/wikipedia/commons/f/f4/Noise_salt_and_pepper.png"

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 82829  100 82829    0     0   171k      0 --:--:-- --:--:-- --:--:--  172k


In [11]:
!curl -O "https://upload.wikimedia.org/wikipedia/commons/d/d2/512x512-Gaussian-Noise.jpg"

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
 89 88488   89 79128    0     0   163k      0 --:--:-- --:--:-- --:--:--  164k
100 88488  100 88488    0     0   180k      0 --:--:-- --:--:-- --:--:--  181k


In [12]:
!curl -O "https://upload.wikimedia.org/wikipedia/en/0/0a/Locator_Grid_double_size.png"

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  7467  100  7467    0     0  27584      0 --:--:-- --:--:-- --:--:-- 28071


In [13]:
import numpy as np

In [17]:
matrix33 = np.arange(9)
matrix33.shape = (3, 3)
matrix33

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### 怎麼取得總合

In [19]:
matrix33.sum()

36

In [20]:
np.sum(matrix33)

36

### 怎麼取得平均值

In [21]:
matrix33.mean()

4.0

In [22]:
np.mean(matrix33)

4.0

In [28]:
np.sum(matrix33 / len(matrix33.ravel()))

4.0

In [38]:
kernel = np.ones_like(matrix33)
kernel

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [36]:
np.sum(matrix33 * kernel / len(kernel.ravel())

3.9999999999999996

## 4 x 4 的影像, 要怎麼做 medium filtering

In [42]:
matrix55 = np.arange(4*4)
matrix55.shape = (4,4)
matrix55

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [43]:
kernel

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [45]:
matrix55[0:3, 0:3]

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10]])

In [48]:
np.sum(matrix55[0:3, 0:3] * kernel / 9)

5.0

In [49]:
np.array([
    [np.sum(matrix55[0:3, 0:3] * kernel / 9), np.sum(matrix55[0:3, 1:4] * kernel / 9)],
    [np.sum(matrix55[1:4, 0:3] * kernel / 9), np.sum(matrix55[1:4, 1:4] * kernel / 9)]])

array([[ 5.,  6.],
       [ 9., 10.]])

In [50]:
from scipy import ndimage

In [51]:
ndimage.convolve

<function scipy.ndimage._filters.convolve(input, weights, output=None, mode='reflect', cval=0.0, origin=0)>