前面的課

https://github.com/vcdemy/20240328/blob/main/20240328%E7%AD%86%E8%A8%98.ipynb

https://github.com/vcdemy/20240411/blob/main/20240411.ipynb

https://github.com/vcdemy/20240418/blob/main/20240418%E7%AD%86%E8%A8%98.ipynb

https://github.com/vcdemy/20240425/blob/main/20240425%E7%AD%86%E8%A8%98.ipynb


* numpy
    * 基本運算
    * indexing
    * slicing
    * clip
    * ravel
* 影像處理基本操作
    * 開啟檔案
        * PIL
        * skimage
        * cv2
    * 圖片縮放
        * thumbnail
        * resize
    * 圖片旋轉
    * 灰階轉換
* 影像處理再階一點點
    * 裁切
    * 貼圖
    * 嵌字
    * 圖層操作
    * histogram
    * thresholding

In [5]:
# 圖
lena_url = "https://upload.wikimedia.org/wikipedia/en/7/7d/Lenna_%28test_image%29.png"
moon_url = "https://upload.wikimedia.org/wikipedia/commons/e/e1/FullMoon2010.jpg"

In [3]:
import numpy as np

# numpy

## 四則運算

In [6]:
a = np.array([1, 2, 3, 4])
b = np.array([7, 8, 9, 10])

In [7]:
a + b

array([ 8, 10, 12, 14])

## indexing

In [9]:
a = np.array([1, 2, 3, 4])

In [11]:
a[2]

3

In [12]:
a = np.array([1, 2, 3, 4, 5])

In [16]:
start = 2 - 1
end = 4

a[start: end]
a[1: 4]
a[1: 1 + 3]
# 都一樣

array([2, 3, 4])

In [18]:
img = np.arange(3*3*3).reshape((3, 3, 3))
img

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [24]:
red = img[:, :, 0]
red

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

## Clip

In [27]:
a = np.arange(100)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [32]:
np.clip(a, a_min=30, a_max=70)

array([30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30,
       30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70,
       70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70])


* numpy
    * slicing
    * clip
    * ravel
* 影像處理基本操作
    * 開啟檔案
        * PIL
        * skimage
        * cv2
    * 圖片縮放
        * thumbnail
        * resize
    * 圖片旋轉
    * 灰階轉換
* 影像處理再階一點點
    * 裁切
    * 貼圖
    * 嵌字
    * 圖層操作
    * histogram
    * thresholding