In [2]:
import numpy as np

In [12]:
l = np.arange(3*3*3).reshape((3, 3, 3))

In [5]:
l

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [6]:
l.reshape((3, 3, 3))

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [7]:
l.reshape((3, 9))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [8]:
l.reshape((9, 3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26]])

In [9]:
l

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [10]:
l.reshape((3, 3, 3))[:, :, 0]

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

In [18]:
c = l.copy()
c

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [16]:
b = c[:, :, 2]
c = 
c[:,:, 0], c[:,:, 2] = c[:, :, 2], c[:,:, 0]

In [17]:
c

array([[[ 2,  1,  2],
        [ 5,  4,  5],
        [ 8,  7,  8]],

       [[11, 10, 11],
        [14, 13, 14],
        [17, 16, 17]],

       [[20, 19, 20],
        [23, 22, 23],
        [26, 25, 26]]])